### ISSUE TITLE
add support for Lethal Emotes API emoting 

### ISSUE THREAD

**Issue by broilerosu** [qwbarch/lc-mirage#13]
it has a sync emote feature on v so if someone is emoting it could be funny if it syncs up 

but even better it has a random emote feature binded to f it will play a random emote between every emote mod you have thats linked to lethal emotes api 

https://thunderstore.io/c/lethal-company/p/Gemumoddo/LethalEmotesAPI/

**Comment by qwbarch** [comment]
I think this already works, I was testing another player's modpack and masked enemies were emoting when I see them
