### ISSUE TITLE
The mode works normally, but an issue where all players except the ship and the last user to log in are kicked out.

### ISSUE THREAD

**Issue by Hu-Myo** [qwbarch/lc-mirage#17]
I kept playing, but Disconnect(?) popped up and I couldn't interact with the ship lever
In Korea, someone made a Hangul patch to solve the language barrier
However, when you log in to the game with the Korean patch, all the players who log in were kicked out except for the last player who logged in, and you could only access it if you removed the Korean patch
I thought that there was definitely a problem with the issue of not being able to access the game when I patched the Korean and not being able to lower the lever, so I decided to report this

You can get the Korean patch here
https://www.mediafire.com/file/i1xdhylf42q00kf/LethalCompanyKorean_v49b3.zip/file
This is the modpack code that I had an issue with.
018d8372-064a-23ea-4d13-6b5f42dabff1
[LogOutput.log](https://github.com/qwbarch/lc-mirage/files/14193449/LogOutput.log)

**Comment by qwbarch** [comment]
Does this happen with only Mirage installed? It'll be easier to debug the issue if it's the only factor

**Comment by Hu-Myo** [comment]
I'll give it a try

**Comment by Hu-Myo** [comment]
When I checked, it doesn't seem to be a problem with the Hangul patch, but an error code pops up on the console
I'm not sure if it's compatible with AdvancedCompany, so even if I put it in and test it together, I get the same error as when I didn't put the mod

I'll attach the logs
[Warning: Unity Log] [Dissonance:Recording] (12:46:49.333) BasePreprocessingPipeline: Lost 960 samples in the preprocessor (buffer full), injecting silence to compensate
[Warning: Unity Log] [Dissonance:Recording] (12:46:49.334) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.2333506)
[LogOutput.log](https://github.com/qwbarch/lc-mirage/files/14194050/LogOutput.log)

**Comment by Hu-Myo** [comment]
I don't think it's a Korean patch issue
I don't know why I get that Warning error, but if it's normal, it doesn't matter.
I think it's because it's not compatible with other mods in my modpack

**Comment by qwbarch** [comment]
Can you test it with only mirage enabled? I just want to make sure it's not an issue with mirage specifically

**Comment by Hu-Myo** [comment]
Here it is
[LogOutput.log](https://github.com/qwbarch/lc-mirage/files/14194412/LogOutput.log)

**Comment by qwbarch** [comment]
Thanks, I'll take a look when I'm on my pc tonight

**Comment by qwbarch** [comment]
@Hu-Myo What enemies do you have enabled for voice mimicking? I don't see ``MaskedPlayerEnemy`` spawned, so I'm assuming you're trying to use the mod with different enemies?

Could you try running the mod again with the new version? I've fixed a couple issues that *could* be related to what you were experiencing

**Comment by Hu-Myo** [comment]
I've just returned from leaving
What should I test?
Do I test just one mode? Or do I test a modpack that I've raised an issue with?

**Comment by Hu-Myo** [comment]
The enemies I had active were Masked, BaboonHawk, Bracken, Spider, CoilHead, EarthLeviathan, EyelessDog, ForestKeeper, Ghostgirl, HoardingBug, Jester, Nutcracker, SnareFlea, SporeLizard, and Thumper.

**Comment by Hu-Myo** [comment]
I'll post the logs
This is a solo log with just Mirage in it
[LogOutput.log](https://github.com/qwbarch/lc-mirage/files/14207826/LogOutput.log)

This is a solo log with the first modpack I posted.
[LogOutput.log](https://github.com/qwbarch/lc-mirage/files/14208037/LogOutput.log)

**Comment by qwbarch** [comment]
The log with just mirage in it looks fine, which I'm assuming it worked right?

> Due to the large number of mods, I will take some time to disable all mods in the modpack and enable them one by one to find out which ones are conflicting.

Yeah this is the painful part of making a large modpack sadly. If there's any mirage-specific conflicts then I'll try to look into a fix, otherwise there's not much I can do to help, sorry

> It's the beginning of the Chuseok holiday here in Korea, so I won't be able to pay attention to it for 3 days.

Hope you have a happy lunar new year!

**Comment by Hu-Myo** [comment]
[Log2.log](https://github.com/qwbarch/lc-mirage/files/14232893/Log2.log)
[Log3.log](https://github.com/qwbarch/lc-mirage/files/14232894/Log3.log)

**Comment by qwbarch** [comment]
Monsters not spawning is definitely not because of logs, the logs is *due* to them not spawning.  

Again my apologies for not being able to help, but I can only help with mirage-specific issues, and from what it sounds like, it's likely not coming from mirage.

> And this is a different, off-topic issue, but when the player turns into a zombie, if you're using a mod that names maps like PlayerMapNumbers, the zombie's body will show the same name that appears on the map.

Isn't this intended? The spawned masked enemy should try to copy the player to the best of its abilities.  
I'm assuming ``PlayerMapNumbers`` handles using the player's number on the map after mirage sets the mimicking player of the masked enemy.

**Comment by Hu-Myo** [comment]
> Again my apologies for not being able to help, but I can only help with mirage-specific issues, and from what it sounds like, it's likely not coming from mirage.

I think so too, I'll have to ask the other mods about this, I don't think there are any issues with Mirage at the moment.

> Isn't this intended? The spawned masked enemy should try to copy the player to the best of its abilities.
> I'm assuming `PlayerMapNumbers` handles using the player's number on the map after mirage sets the mimicking player of the masked enemy.

I think my explanation was short.
The numbers, which are technically a feature of the `PlayerMapNumbers` mod, also appear in the navigation, but when the player is changed to Masked, a giant number is generated on the chest looking up at the sky.

I didn't have a play image to refer to, so here's a hand-drawn reference image
![미라지버그](https://github.com/qwbarch/lc-mirage/assets/79264823/8417d134-3672-426a-badb-2d54d26f746a)
The exact same situation as in the picture above was confirmed in-game
Not sure if this is a Mirage issue or a `PlayerMapNumbers` mod issue

**Comment by qwbarch** [comment]
It's definitely an issue with ``PlayerMapNumbers`` that you should notify them about. 
Cosmetic changes should, for the most part, be applied to masked enemies by those mods themselves

**Comment by Hu-Myo** [comment]
We'll report any issues with other mods to their developers.

I don't think there are any unplayable issues at the moment
We are not currently experiencing any errors like the original topic.
I think it's safe to assume that this issue has been resolved.

If we run into compatibility issues with other mods, we'll create a new post about it.

**Comment by qwbarch** [comment]
Sounds good, glad you were able to figure out the issue!
