### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by CatsArmy** [qwbarch/lc-mirage#20]
Personally I would move all features that arent dependent on the recording part of the mod to a different one.

Also unsure if it's possible to do or if it requires the voice recognition mod but I would try detecting if the audio is pretty much empty or if you are muted via the mute mod as I didn't play alot and it's all ready 17mb

**Comment by CatsArmy** [comment]
- Maybe add a config to just disable the all tweaks so it only keeps the skin walker like functionality (with the networking)

**Comment by CatsArmy** [comment]
That's fair but maybe consider what I suggested in the last comment

**Comment by CatsArmy** [comment]
Ty

**Comment by qwbarch** [comment]
Made the README explain how to disable the extra features: <https://github.com/qwbarch/lc-mirage#what-configuration-options-should-i-use-for-a-more-vanilla-experience>
