### ISSUE TITLE
Add skin walker support 

### ISSUE THREAD

**Issue by CatsArmy** [qwbarch/lc-mirage#21]
Add support for it to also use recordings from the skin walker folder

**Comment by qwbarch** [comment]
Why do you need to use skinwalkers at the same time? Mirage already plays synced voices

**Comment by CatsArmy** [comment]
I phrased it poorly I ment it would detect recording that were saved by skin walker and add them to the pool of voice lines

**Comment by CatsArmy** [comment]
Perhaps it would just import them to the mirage save folder

Unless skin walker doesn't have a folder for each player which them conflicts with the vision you have for this nod

**Comment by qwbarch** [comment]
Skinwalkers has recordings of all players, except for the local player itself.  
For mirage, it *only* contains recordings of the local player. I don't see why anyone would even need something like this anyways, when you can copy audio files to the mirage folder yourself.
