### ISSUE TITLE
NOT ONLY MIMICS 

### ISSUE THREAD

**Issue by VadPoMos** [qwbarch/lc-mirage#26]

**Comment by qwbarch** [comment]
You mean voice mimicking for non-masked enemies? It's already supportef in the config

**Comment by VadPoMos** [comment]
Yep, I’ve noticed that. You just don’t have such an option described in the
description of the mod, and my bad that I hadn’t checked the mod before
suggesting so.

But anyway, try to add this feature in the actual description. I think it
would attract people more if they know from the beginning that mod works
not only with Masked enemies
