### ISSUE TITLE
Suggestion: Masked on any moon

### ISSUE THREAD

**Issue by its0v3r** [qwbarch/lc-mirage#27]
The only reason I'm still using MaskedEnemyOverhaul is so the masked can spawn in any moon. It would be a cool adittion to this mod!

**Comment by qwbarch** [comment]
I might add spawn control for masked enemies later on but not anytime soon.
If you're going to use MEO, I recommend using the fork instead, with the mirage compatibility config option enabled

**Comment by its0v3r** [comment]
Good to know, thanks man!

**Comment by qwbarch** [comment]
I don't think I'll be adding spawn control to Mirage actually, since people generally have a mod that does that already
