### ISSUE TITLE
Incompatible or causing problems with AdvancedCompany

### ISSUE THREAD

**Issue by Hu-Myo** [qwbarch/lc-mirage#32]
Spawning Masked causes bugs with `EnemyAi` and `MaskedPlayerEnemy`
Could you please check compatibility with `AdvancedCompany`?
[LogOutput.log](https://drive.google.com/file/d/1u3biDXM4ShEObZCmiotwCsMLAl0pms5F/view?usp=sharing)

**Comment by qwbarch** [comment]
There's no incompatibilities with ``AdvancedCompany``. It's likely another mod conflicting with mirage.
Did this only start to happen after the latest update for mirage? (v1.0.14)

**Comment by Hu-Myo** [comment]
This was an error that was slightly visible in 1.0.6
Today I had a Masked that summoned and then froze in place while I was working on it

**Comment by qwbarch** [comment]
Oh was the last version you used of Mirage 1.0.6? I'll have to investigate some more

**Comment by qwbarch** [comment]
> This was an error that was slightly visible in 1.0.6 During my work today, I had a Masked that spawned through a vent and then froze in place

For these masked enemies that freeze right after they spawn through a vent, do they still have their mask textures on?
I've been told that masked enemies can get stuck in the vents in vanilla too, so it might not be from mirage

**Comment by Hu-Myo** [comment]
Yes Mask Texture is on
But I've only seen that bug once today, and before that, Masked is behaving fine
But the error logs are still coming in.

It's spewing out too many logs and dropping frames.

It's always only happened when Masked spawns.
The mods I use that are related to Masked are `Mirage` and [MaskRemover](https://thunderstore.io/c/lethal-company/p/Poseidon/MaskRemover/)

**Comment by qwbarch** [comment]
Thanks, currently trying to figure out what the issue is with a bunch of folks on discord. I'll report back here if anything is found

**Comment by qwbarch** [comment]
@Hu-Myo Are you using ``AtlasAbyss``, could you actually send a profile code as well? I just want to take a quick look at the mods.
I don't have a solution yet, just trying to take a look

**Comment by Hu-Myo** [comment]
> @Hu-Myo Are you using `AtlasAbyss`, could you actually send a profile code as well? I just want to take a quick look at the mods. I don't have a solution yet, just trying to take a look

No, `AtlasAbyss` is not being used.
This is because Moons mods that use the same LLL as this one have a bug where the `RandomSeed` doesn't go through when using the `Korean patch` made by someone in my country, Korea.

If you have any code in your mod code that recognizes items, this could be a problem.
This `Korean patch` renames the item with a different name in Korean

Here is the code for my mod
018db19f-ac3a-3b3b-7ddf-9253136a3fc2

**Comment by qwbarch** [comment]
This seems to be a problem with english users as well, so rest assured the conflict is mot with the korean patch.
I think you're right that it's an issue with LLL in general, since other modded moons *seem* to be having a similar issue (at least with mirage installed it seems).

I'll try your modpack out to see if I can replicate the error

**Comment by Hu-Myo** [comment]
https://youtu.be/xbXmfjOYtzA

I've taken a video
When Masked spawns from an LLL-added internal map, it gets stuck like this, throwing a `MaskedPlayerEnemy.LookAtFocusedPosition` error

I think it's an error in LLL mode when Masked spawns and gets stuck there.

I'll let you know if this happens on the base map as well when I confirm it.

Below is the log from the game where the video was taken
Masked spawned starting at line 7198
https://drive.google.com/file/d/1fONjnL8UDrjPdOwVkU_fGr-J_Extnwpx/view?usp=sharing

**Comment by qwbarch** [comment]
Thanks a lot for all the details! I'm out on a trip right now but I'll take a look probably on monday.

This looks like the same errors some people are reporting on discord, so this will help a lot for figuring out the issue

**Comment by qwbarch** [comment]
@Hu-Myo Could you try if the latest version (``v1.0.15``) fixes this?

**Comment by Hu-Myo** [comment]
I'm playing solo and it seems to be fixed
I didn't get any errors at all
I'll check if it happens with more than 2 people when I get a chance

**Comment by Hu-Myo** [comment]
I haven't seen any errors in 2 hours in a room starting at 10 people
Everything seems to be fixed, thank you

**Comment by qwbarch** [comment]
Good to know, thanks for confirming!
