### ISSUE TITLE
[Issue] A mechanism conflict from another mod

### ISSUE THREAD

**Issue by CoolLKKPS** [qwbarch/lc-mirage#35]
So im doing my modpack, and our team are really enjoy Backroom mods, so i hope u can fix that
my Dark Hour Modpack code: 018dc3cd-5a10-cdc9-8616-0d9a3b1e4b26
Do not run 2 game programs in the same device, u might will encounter savefile corrupt
(Eng Language by Default now)

So, if u using [Real Backrooms Patch](https://thunderstore.io/c/lethal-company/p/TestAccount666/Real_Backrooms_Patch), if u tp to backroom by received lethal dmg (for my test, fall dmg), the game should be will create a faked dead body in the original world, but that doesn't work for some reason, i did turn on spawn masker on dead in Mirage mod, so i pretty sus that function.
if don't have fake body, tp back to fake body function won't work even, that will make huge issues like spawn player in the sky, no sure that's good thing or bad thing but, for mechanism that's bad thing, but for backroom that's good thing i guess? hope u can fix that

! in recently my modpack update, i remove the mechanism about deadbody turn into masker, to make the game can work properly !

**Comment by qwbarch** [comment]
I'll have to take a look in a couple days, probably will be busy for a bit so I can't test the modpack for now

**Comment by CoolLKKPS** [comment]
Don't want ur savefile corrupted, do not use my previous modpack code

**Comment by qwbarch** [comment]
It corrupted your save?

**Comment by CoolLKKPS** [comment]
uh i mean... my modpack, not ur issue, if u try to investigate my modpack, just make sure do not use previous one, that can lose character data and some savedata

**Comment by qwbarch** [comment]
Ah sounds good. I'll probably test around monday or so

**Comment by qwbarch** [comment]
Could you actually try to see if this still conflicts with the latest update?  
``v1.0.15`` fixes a different issue, but it could be related to this, so might as well try and see if it works first

**Comment by CoolLKKPS** [comment]
> Could you actually try to see if this still conflicts with the latest update? `v1.0.15` fixes a different issue, but it could be related to this, so might as well try and see if it works first

ok will test that tomorrow

**Comment by CoolLKKPS** [comment]
sry i have to say, i can't test that in time, still need more time so i can get back to test, really sry

**Comment by qwbarch** [comment]
All good, let me know if you end up testing it

**Comment by CoolLKKPS** [comment]
@qwbarch ok after i tested, should be not Mirage problem, for some how that patch didn't spawn fake dead body after player tp to the backroom, but i hope u can prepare that, for now [Real_Backrooms_Patch](https://thunderstore.io/c/lethal-company/p/TestAccount666/Real_Backrooms_Patch) is still malfunction, but who know when in the future that patch worked
and i hate Thunderstore didn't provide comment feature... in my region i can't use discord

**Comment by qwbarch** [comment]
Your best bet would probably to contact that mod's author tbh, I'm not entirely sure what I could do to prevent the conflict

**Comment by CoolLKKPS** [comment]
thx, i will
