### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ZigzagAwaka** [qwbarch/lc-mirage#39]
Just wanted to post some suggestions for this mod :
- make it so masked can spawn (naturally) on every moon given a weight chance that can be configured
- make masked only speak with the voice of the player they are mimicking
- i saw some videos where the masked can do emote ? (but never saw this myself) Is that because of another mod, or is it actualy a feature of Mirage? If so that could be nice to disable it via config option
- make it so masked have their username above them, but we can only see that if we are close to them, similar to the way we can see other players username while beeing close to them
- make it so masked can have tools (flashlight, shovel) and/or scraps in their hands to deceive players even more
- maybe tweak the AI of masked ? For example when they see a player, instead of stopping and staring for a little bit, they could try to deceive the player by speaking something or by getting away for a while and then come back to kill the player? <- don't really know if it's a good idea tbh

**Comment by qwbarch** [comment]
> make it so masked can spawn (naturally) on every moon given a weight chance that can be configured

I don't think I'll add this to Mirage as players often have spawn control mods installed already (such as ``AdvancedCompany``)

> make masked only speak with the voice of the player they are mimicking

This is already a feature

> i saw some videos where the masked can do emote ? (but never saw this myself) Is that because of another mod, or is it actualy a feature of Mirage? If so that could be nice to disable it via config option

This is from another mod. Mirage does not have anything to do with emotes

> make it so masked have their username above them, but we can only see that if we are close to them, similar to the way we can see other players username while beeing close to them

While it's not currently a feature, this is something I plan on adding in the future (although not anytime soon). In the meantime, I recommend using a mod that hides the player names, such as [HidePlayerNames](https://thunderstore.io/c/lethal-company/p/Monkeytype/HidePlayerNames/)

> make it so masked can have tools (flashlight, shovel) and/or scraps in their hands to deceive players even more

This is planned, but it will take awhile before I even have time to attempt this

> maybe tweak the AI of masked ? For example when they see a player, instead of stopping and staring for a little bit, they could try to deceive the player by speaking something or by getting away for a while and then come back to kill the player? <- don't really know if it's a good idea tbh

Planned as well, but again, will take awhile before I get to this part. And even if I do get to it, there's no guarantees I'll be able to execute it properly, so we'll have to see

**Comment by qwbarch** [comment]
Yeah no worries, I assumed you were probably asking before you decide to try it out or not
