### ISSUE TITLE
Thunderstore upload status

### ISSUE THREAD

**Issue by MythicManiac** [qwbarch/lc-mirage#4]
Hey, just wanted to drop by to mention your Thundertsore upload got flagged for manual review by some automation in case you're wondering what's going on. Should take 24h at most for it to be sorted out

**Comment by qwbarch** [comment]
> Hey, just wanted to drop by to mention your Thundertsore upload got flagged for manual review by some automation in case you're wondering what's going on. Should take 24h at most for it to be sorted out

Ah I wasn't looking at github so I didn't notice this until now. Thank you for the notice!

**Comment by qwbarch** [comment]
On the off chance this doesn't get approved after a day, is there anything I could provide that would help make it easier to review whatever that needs to be checked?

**Comment by MythicManiac** [comment]
This should be approved now, although subsequent updates to it might re-trigger the same automation (we're still working on making it a bit less destructive on that front; current state of the system is what was quick to implement when it became necessary).

As for what you can do to make it less likely to get flagged or easier to review, bundling in less dependency dlls to the same package would go a long way. I can infer that it's probably not the easiest thing to do in your case given the uses of F#, but if you want to put actual effort into it, you could e.g. bundle the F# & other core 3rd party dependencies to their own packages and use those via dependency relations.

Bundling them all in the same package isn't a problem strictly speaking, it just takes longer to review for us

**Comment by qwbarch** [comment]
I'll definitely look into doing that. Thanks a lot for the help!

**Comment by qwbarch** [comment]
@MythicManiac Sorry for the ping, but it looks like my package was closed again. Why's that?
https://thunderstore.io/c/lethal-company/p/qwbarch/Mirage/
