### ISSUE TITLE
bug: penalty for death bug

### ISSUE THREAD

**Issue by TFlinchu** [qwbarch/lc-mirage#43]
If any player has died during the match, it will always say you have incurred a $200 penalty, no matter how much you have. 

On top of this, it also removes any penalty you would have had, as no money is actually removed from your balance.

I have tested the 3 dependencies on their own, and the bug only happens when mirage itself is enabled.

**Comment by qwbarch** [comment]
Sorry this comes from a legacy feature of Mirage that I forgot to fisable by default. 
Set the credits penalty to "true" in the config to get the vanilla behaviour. I will change the default in the next update (and remove this "feature" in a future major update)
