### ISSUE TITLE
1.20bug

### ISSUE THREAD

**Issue by 1410677474** [qwbarch/lc-mirage#48]
Unable to load the game

**Comment by DaXcess** [comment]
Issue described in more detail at #49

**Comment by VirusTLNR** [comment]
> Issue described in more detail at #49

so you added LobbyCompatibility, then it worked? i was in the middle of testing something else then came back to this, so was about to do that test.. however, if you check the coding.. afaik.. the "SoftDependency" means LobbyCompatibility shouldent be required.

**Comment by VirusTLNR** [comment]
these are the errors in the console. it does these, repeats them again, then spams the last 3 errors repeatedly non-stop... there in causing the above mentioned softlock.

installing "LobbyCompatibility" does seem to fix it.

`[Info   :Better Lobbies] Entered lobby successfully!
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Dissonance.Integrations.Unity_NFGO.NfgoServer.Connect () (at <af9b1eec498a45aebd42601d6ab85015>:IL_002D)
Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].StartServer (TServerParam connectParams) (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_0036)
Dissonance.Networking.BaseCommsNetwork`5+Session[TServer,TClient,TPeer,TClientParam,TServerParam].StartServer () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_0000)
Dissonance.Networking.BaseCommsNetwork`5+Session[TServer,TClient,TPeer,TClientParam,TServerParam].Enter () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_001E)
Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].ChangeState (Dissonance.Networking.BaseCommsNetwork`5+IState[TServer,TClient,TPeer,TClientParam,TServerParam] newState) (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_0012)
Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].LoadState () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_000E)
Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].Update () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_0009)
Dissonance.Integrations.Unity_NFGO.NfgoCommsNetwork.Update () (at <af9b1eec498a45aebd42601d6ab85015>:IL_01B9)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Unity.Netcode.NetworkManager.NetworkUpdate (Unity.Netcode.NetworkUpdateStage updateStage) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004C)
Unity.Netcode.NetworkUpdateLoop.RunNetworkUpdateStage (Unity.Netcode.NetworkUpdateStage updateStage) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0021)
Unity.Netcode.NetworkUpdateLoop+NetworkPostLateUpdate+<>c.<CreateLoopSystem>b__0_0 () (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Unity.Netcode.NetworkConnectionManager.PollAndHandleNetworkEvents () (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)
Unity.Netcode.NetworkManager.NetworkUpdate (Unity.Netcode.NetworkUpdateStage updateStage) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0018)
Unity.Netcode.NetworkUpdateLoop.RunNetworkUpdateStage (Unity.Netcode.NetworkUpdateStage updateStage) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0021)
Unity.Netcode.NetworkUpdateLoop+NetworkEarlyUpdate+<>c.<CreateLoopSystem>b__0_0 () (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Unity.Netcode.NetworkManager.NetworkUpdate (Unity.Netcode.NetworkUpdateStage updateStage) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0040)
Unity.Netcode.NetworkUpdateLoop.RunNetworkUpdateStage (Unity.Netcode.NetworkUpdateStage updateStage) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0021)
Unity.Netcode.NetworkUpdateLoop+NetworkPreUpdate+<>c.<CreateLoopSystem>b__0_0 () (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Dissonance.Integrations.Unity_NFGO.NfgoClient.Connect () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0016)
Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].StartClient (TClientParam connectParams) (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_0116)
Dissonance.Networking.BaseCommsNetwork`5+Session[TServer,TClient,TPeer,TClientParam,TServerParam].StartClient () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_0000)
Dissonance.Networking.BaseCommsNetwork`5+Session[TServer,TClient,TPeer,TClientParam,TServerParam].Update () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_00F2)
Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].Update () (at <71dd734e1ae34dcbb7fcdfa8af2afae2>:IL_000F)
Dissonance.Integrations.Unity_NFGO.NfgoCommsNetwork.Update () (at <af9b1eec498a45aebd42601d6ab85015>:IL_01B9)`

**Comment by qwbarch** [comment]
Thanks for the report, it's fixed hotfixed in ``v1.2.1``
