### ISSUE TITLE
1.2.0 missing dependency LobbyCompatibility

### ISSUE THREAD

**Issue by DaXcess** [qwbarch/lc-mirage#49]
Mirage 1.2.0 added compatibility for the LobbyCompatibility mod, however Mirage either does not have LobbyCompatibility as a dependency (Thunderstore), or the mod does not properly check if LobbyCompatibility is present.

Starting a game with Mirage installed and **without** LobbyCompatibility causes the game to softlock due to missing Assembly `BMX.LobbyCompatibility`.

Just thought I'd report this since people will freak out wondering why their game doesn't start.

Current workarounds are:
- Downgrade to previous Mirage version
- Add LobbyCompatibility to your mods list

**Comment by qwbarch** [comment]
Thanks for the report, it's fixed hotfixed in ``v1.2.1``
