### ISSUE TITLE
Things to add/support

### ISSUE THREAD

**Issue by qwbarch** [qwbarch/lc-mirage#5]
Current priority:

- [x] Make the ``spawn masked enemy on player death`` chance configurable
- [x] Make natural spawns mimic a random person (chosen when it spawns)
- [x] Support voice activity
- [ ] Capping the storage used by audio clips (and also make it optional to delete in between rounds/games)
- [x] Stop mimicking voice when masked enemy is hiding in the ship
- [x] Make mimicked player not able to hear a mimic if it's themselves (configurable)

Lower priority, but will almost certainly do:
- [ ] ~~Support ModelReplacementAPI~~
- [ ] ~~Support [LethalVRM](https://thunderstore.io/c/lethal-company/p/Ooseykins/LethalVRM/)~~
- [x] ~~Support AdvancedCompany cosmetics~~
- [ ] ~~Support models that don't use an API, maybe using the player's model will be enough to support all custom outfits. Example: [CompanyIssuedProtogen](https://thunderstore.io/c/lethal-company/p/ScottyFoxArt/CompanyIssuedProtogen/)~~
- [ ] ~~Instead of spawning the masked enemy immediately upon death, make it optional where you can have it spawn when it's outside players' povs~~
- [x] Support TooManyEmotes (makes masked enemies emote when first encountered)
- [ ] Support name tags above mimicked masked enemies
- [ ] Make mouth dogs attack masked enemies when they speak (configurable)

Eventually need to do:
- [ ] Fix the audio playback timings, it currently plays much earlier on the host than on the clients

**Comment by qwbarch** [comment]
Cosmetic mods I can use to test with (for AC):
- EquipmentCompany
- ComedyAndTragedyMasks
- Gridian_Cosmetics
- BensCosmetics

**Comment by TomEFFENJones** [comment]
Sorry if this is the wrong area to ask, but does this delete the voice clips afterwards or after a certain threshold like Skinwalkers?  I prefer your implementation, but don't want to worry about storage.  Again, sorry if this is not the place to ask!

**Comment by cangming99** [comment]
“Support name tags above mimicked masked enemies" I really need this feature! May I conveniently inquire about the current progress? Thank you for developing this mod; it’s very interesting.

**Comment by qwbarch** [comment]
@cangming99 I'm currently working on features for v2 instead of things on this list.  
As an alternative in the meantime, I recommend using ``GeneralImprovements`` with the config enabled for removing players tags, to make it harder to spot the difference between players and masked enemies
