### ISSUE TITLE
[Issue] will block vanilla player from join the game

### ISSUE THREAD

**Issue by CoolLKKPS** [qwbarch/lc-mirage#50]
same as topic, display "The server host has already landed their ship, or they are still loading in."

**Comment by CoolLKKPS** [comment]
and don't have any error log

**Comment by qwbarch** [comment]
Mirage is required on all clients, so this makes sense. It's probably due to the fact that they. vanilla players are missing the network prefabs registered by mirage

**Comment by CoolLKKPS** [comment]
ok, but can u add vanilla support, bcz actually in v49 mirage can work with vanilla, i just want my experience have some challenge

**Comment by qwbarch** [comment]
I don't see how Mirage even works in vanilla for other clients who don't have it, considering the networking (which is required for syncing the voices) can only be done if it's on every client.

Why not just have every client download it?

**Comment by CoolLKKPS** [comment]
so in previously i use Skinwalkers and MaskedEnemyOverhaul to play with vanilla, i want masker have more challenge, but both 2 mods are not really useful and the voice audio are not synced with other who has mirage
yea and very only can cause when i enable mirage, so in v49 that can work, and i really like it, so i hope mirage can continue support vanilla

**Comment by CoolLKKPS** [comment]
not "who has mirage" but just little typo

**Comment by qwbarch** [comment]
I think I'm misunderstanding you, so every player in your lobby does have mirage installed?
Mirage does work fine in v50 the last time I tested it. Is that the issue you're having?

**Comment by CoolLKKPS** [comment]
ok i might need to turn on my computer...
no just want mirage only work for people who has mirage, and won't block vanilla from joining bc mirage current are not change network related things that really necessary, config will sync to host if im right, but uh i actually not expect u not plan to let mirage support vanilla, bc mirage works really well in previous

**Comment by qwbarch** [comment]
Ah so the expectation is that it doesn't work on vanilla, it just allows the player to at least join and play the game?
I'm not sure why it'd allow vanilla players to join in v49 and not in v50 though, sounds like zeekers made some changes to detect mods maybe.
Either way I didn't explicitly remove the ability for vanilla clients to join, and I don't plan on looking into it either, sorry

**Comment by CoolLKKPS** [comment]
ah ok, but really, hope mirage can continue support vanilla bc that will be real nice

**Comment by qwbarch** [comment]
I'm focused on v2 so I won't have time to look into this, sorry
