### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by IamZulio** [qwbarch/lc-mirage#51]
After starting a game, the camera presents a bug that makes the game impossible

![image](https://github.com/qwbarch/lc-mirage/assets/129312741/65214a04-71cf-4cb5-b8b0-70cf8cbdd2de)

**Comment by TheUnknownCod3r** [comment]
Yep can confirm, removing Mirage fixes the bug.

**Comment by qwbarch** [comment]
I need to update Mirage to support the latest version of the game, sorry about that

**Comment by qwbarch** [comment]
Fixed in the latest version of Mirage. I'm just waiting for ThunderStore to accept my package, it seems to be a bit bugged right now.

**Comment by TheUnknownCod3r** [comment]
legend, tysm for the fix <3
