### ISSUE TITLE
Why make an entire new implementation of mimics instead of hooking onto RugBugs mod?

### ISSUE THREAD

**Issue by Sentrymon** [qwbarch/lc-mirage#7]
As title says. I'm simply wondering over your choice to make the whole mod from scratch instead of adding onto RugBugs skinwalker mod. I feel like it'd been a lot more convenient to require the skinwalker mod and then just high jacking it, disable the features you don't need and use it's built in audio recording features and just make the playback global. 

Alternatively "borrowing" their code for the recording part as your implementation seems to have a few limitations. 

Don't take this as negative feedback. It's looking like it's gonna be a great mod down the line, probably replacing "the original"

**Comment by qwbarch** [comment]
@Sentrymon Skinwalkers is fundementally different underneath the hood. The fact that it's client-side only already makes it very different.

I appreciate the feedback, just wanted to clarify that it just doesn't work the same so that can't really happen

**Comment by CatsArmy** [comment]
well i mean if they both do the same thing then maybe you should create a dummy version of skinwalker so it doesnt overlap or something idk lul @qwbarch
