### ISSUE TITLE
Config Requests: All enemy's mimic players and option to keep masks visible

### ISSUE THREAD

**Issue by Wolfcl0ck** [qwbarch/lc-mirage#8]
Hello. I think this mod is a really nice addition to the mods I've been using with friends, I just have a few requests about configurable options for the mod.
First, I think that, given that this mod actually networks voices, it would be nice to have an option to allow for voice mimicry from all enemies instead of just the masked enemies. Some people would probably prefer options to do this on a per-enemy basis, but to be honest, I think a toggle for all enemies or *just* mask mimics would be more than sufficicent.
Second, while I understand the reason for removing masks and the arm animation, I think it would also be nice to allow that as a configurable option. For my friends and I, I think it might be a bit too over-the-top if the masked enemies looked 100% identical to us without an available option to revert that.

**Comment by qwbarch** [comment]
I can definitely add a configuration option for removing masks and the arm animation.

As for allowing other enemies to mimic voices, it'd be simple to add, but the only reason I haven't done so yet is because I don't want an exact copy of rug's mod. Perhaps I'll add it in the future, but I'm going to have to hold off from it for now

**Comment by Wolfcl0ck** [comment]
Has someone else done a mod that has networked voice mimics for all enemies?

**Comment by qwbarch** [comment]
As far as I know, no, which is why I even made mine

**Comment by qwbarch** [comment]
Y'know what, maybe I will implement it soon. I think I'll ask around to see how many people want this feature first though

**Comment by Wolfcl0ck** [comment]
Dope. If you choose to do so, I look forward to it, my friend group has been itching for a mod like this for well over a month now.

**Comment by qwbarch** [comment]
Yep I asked around on discord and it seems like people do want it, so I'll try and include it in the update tonight, or tomorrow if I don't finish it today.

I'll ping you here when it's finished

**Comment by qwbarch** [comment]
@Wolfcl0ck Voice mimicking on all vanilla monsters is supported now (at least if there's no bugs).  
I didn't test it much though, so hopefully there's no issues with it.
